description: >
    Implement properties to indicate the element cooling type (air, water, etc.).
properties:
    - name: AirCooled
      type: boolean
      description: >
          The element uses air/fans for cooling when set to true.
    - name: WaterCooled
      type: boolean
      description: >
          The element uses water for cooling when set to true.
