FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
DEPENDS += " virtual-media "
RDEPENDS_${PN} += " virtual-media "
#SRC_URI_append += "file://0001-Virtual-Media-Master-Session.patch"
#SRC_URI_append += "file://0002-Fixed-Eject-Issue.patch"
SRC_URI_append += "file://0003-nbd-device-configration-for-Multiple-VM-redirection.patch"
SRC_URI_append += "file://0004-Fixed-Eject-Issue-OSP2.2.patch"
SRC_URI_append += "file://0005-Nbd_HandShake_timeout.patch"
