#!/bin/bash
#
# config: 2 30
# @brief: collect the ARPControl Configurations.
#

. $DREPORT_INCLUDE/functions

desc="ARPControl Configurations"
file_name="/etc/arpcontrol"

add_copy_file "$file_name" "$desc"
