#!/bin/bash
#
# config: 2 30
# @brief: collect the IPMI Channel Config information.
#

. $DREPORT_INCLUDE/functions

desc="Channel Config"
file_name="channelconfig.log"
command="cat /usr/share/ipmi-providers/channel_config.json"

add_cmd_output "$command" "$file_name" "$desc"
