#!/bin/bash
#
# config: 2 30
# @brief: Free memory information.
#

. $DREPORT_INCLUDE/functions

desc="free memory"
file_name="freemem.log"
command="free"

add_cmd_output "$command" "$file_name" "$desc"
