#!/bin/bash
#
# config: 2 30
# @brief: Collect interrupts information.
#

. $DREPORT_INCLUDE/functions

desc="interrupts"
file_name="interrupts.log"
command="cat /proc/interrupts"

add_cmd_output "$command" "$file_name" "$desc"
