#!/bin/bash
#
# config: 2 30
# @brief: Collect kernal Ring Buffer information.
#

. $DREPORT_INCLUDE/functions

desc="Kernal RingBuff"
file_name="kernalRingBuff.log"
command="dmesg"

add_cmd_output "$command" "$file_name" "$desc"
