#!/bin/bash
#
# config: 2 30
# @brief: collect the LAN/VLAN Configurations.
#

. $DREPORT_INCLUDE/functions

desc="LAN/VLAN Configurations"
file_name="/etc/systemd/network"

add_copy_file "$file_name" "$desc"
