#!/bin/sh

if [ $# -ne 2 ]
then
	echo "usage: $0 <start|stop> <config>" >&2
	exit 1
fi

action=$1
config=$2
configplusone=$((config+1))
max_instance=6

gadget_name=mass-storage
gadget_dir=/sys/kernel/config/usb_gadget/$gadget_name

if [ `fdisk -l /dev/nbd$config | grep nbd"$config"p1 | wc -l` -eq 0 ]; then
        disk_type=1
else
        disk_type=0
fi

disk_ty=$(( $config % 2))

if [ $disk_ty -eq 1 ]; then
        disk_type=0
fi


case "$config" in
	0)
		nbd_device=/dev/nbd0
		;;
	1)
		nbd_device=/dev/nbd1
		;;
	2)
		nbd_device=/dev/nbd2
		;;
	3)
		nbd_device=/dev/nbd3
		;;
	4)
		nbd_device=/dev/nbd4
		;;
	5)
		nbd_device=/dev/nbd5
		;;
	*)
		echo "invalid config $config" >&2
		exit 1
		;;
esac

set -ex

case "$action" in
	start)

		if [ ! -d "$gadget_dir" ]; then

			mkdir  $gadget_dir
			cd $gadget_dir
			(

			echo "0x1d6b" > idVendor
			echo "0x0104" > idProduct
			mkdir -p strings/0x409
			echo "OpenBMC" > strings/0x409/manufacturer
			echo "Virtual Media Device" > strings/0x409/product
			mkdir -p configs/c.1/strings/0x409
			echo "config 1" > configs/c.1/strings/0x409/configuration
			)

			for ((i=1;i<=max_instance;i++)); do
			mkdir -p functions/mass_storage.usb0/lun.$i
			echo 1 > functions/mass_storage.usb0/lun.$i/removable
			echo 1 > functions/mass_storage.usb0/lun.$i/ro
			done


			echo $disk_type > functions/mass_storage.usb0/lun.$configplusone/cdrom
			echo $nbd_device > functions/mass_storage.usb0/lun.$configplusone/file
			ln -s functions/mass_storage.usb0 configs/c.1
			echo "f0831000.udc" > UDC

			

		else

			cd $gadget_dir

			(	

			echo $disk_type > functions/mass_storage.usb0/lun.$configplusone/cdrom
			echo $nbd_device > functions/mass_storage.usb0/lun.$configplusone/file

			)
		fi
		;;

	stop)
		cd $gadget_dir
		count=0
		for ((k=1;k<7;k++)); do
			if [  -d "functions/mass_storage.usb0/lun.$k" ]; then
				words=`wc -l functions/mass_storage.usb0/lun.$k/file | awk '{print $1}'`;
				if [ $words != 0  ]; then
					count=`expr $count + 1`
				fi	
			fi
		done

                if [ `grep -Fx "nbd$config=1" /etc/nbd-proxy/eject > /dev/null ; echo $?` -eq 0 ]
                then
                        count=`expr $count + 1`
                fi

		if [ $count -eq 1 ];then
			for ((l=1;l<7;l++)); do
				if [  -d "functions/mass_storage.usb0/lun.$l" ]; then
				rmdir functions/mass_storage.usb0/lun.$l
				fi
			done

			(
			rm configs/c.1/mass_storage.usb0
			rmdir functions/mass_storage.usb0
			rmdir configs/c.1/strings/0x409
			rmdir configs/c.1
			rmdir strings/0x409

			)
			rmdir $gadget_dir
		else

			(
			echo  > functions/mass_storage.usb0/lun.$configplusone/file

			)
		fi
		;;

	*)
		echo "invalid action $action" >&2
		exit 1
esac

exit 0

