FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
SRC_URI_append += "file://0001-Added-Sensor-Units-For-WebUI.patch"
SRC_URI_append += "file://0001-Disable-CPU-Sensor.patch"
SRC_URI_append += "file://0002-gpiodigital-sensor.patch"
SRC_URI_append += "file://0003-Added-Sdr-Properties.patch"
SRC_URI_append += "file://0004-psuevent_sel_sensor.patch"
SRC_URI_append += "file://0005-Enabled-PWM-sensors-units.patch"
SRC_URI_append += "file://0006-EvStat-propertypwm.patch"
SRC_URI_append += "file://0007-cpusensor-evstatunit-excehandling.patch"
SRC_URI_append += "file://0008-acpi-sensor.patch"
SRC_URI_append += "file://0009-lowandhighoffset-gpiosensor.patch"
SRC_URI_append += "file://0010-psu-pwm-sensortypes.patch"
SRC_URI_append += "file://0011-Disable-dicrete-sensor.patch"
SRC_URI_append += "file://0012-Disable-Threshold-sensor.patch"
SRC_URI_append += "file://0013-Added-dbus-property.patch"
SRC_URI_append += "file://0014-eventmask-sdrinfo.patch"
SRC_URI_append += "file://0015-Removed-Pwm-sensor.patch"
SRC_URI_append += "file://0016-Properly-clear-sensor-value-on-PowerOff.patch"
SRC_URI_append += "file://0029-Updated-ADCSensor-cpp.patch"
SRC_URI_append += "file://0030-Added-IntelFanConnector.patch"
SRC_URI_append += "file://0031-cpusensor-power-tempsdrinfo.patch"


#Intel patch
SRC_URI_append += "file://0017-Only-allow-drive-sensors-on-bus-2-for-ast2500.patch"
SRC_URI_append += "file://0018-Fix-PSU-PWM-fan-control.patch"
SRC_URI_append += "file://0019-ExitAir-Move-to-GetSensorConfiguration.patch"
SRC_URI_append += "file://0020-Treat-negative-temperatures-as-errors.patch"
SRC_URI_append += "file://0021-NVMeSensor-use-available-interface-for-error-handlin.patch"
SRC_URI_append += "file://0022-PSUSensors-Move-to-GetSensorConfiguration.patch"
SRC_URI_append += "file://0023-Fix-ExitAirTempSensor-calculation.patch"
SRC_URI_append += "file://0024-Fix-ADC-threshold-hysteresis-to-one-percent-of-criti.patch"
SRC_URI_append += "file://0025-Fix-missing-threshold-de-assert-event-when-threshold.patch"
SRC_URI_append += "file://0026-Check-readingStateGood-before-updating-thresholds-pr.patch"
SRC_URI_append += "file://0027-revert-revert-log-debug-information-for-sensor-thres.patch"
SRC_URI_append += "file://0028-Check-readingStateGood-before-updating-thresholds-pr.patch"


SYSTEMD_SERVICE_${PN}_append += " xyz.openbmc_project.hwmontempsensor.service"
