FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
SRC_URI_append += "file://0001-add-ipmi-dcmi-power-command-support.patch"
SRC_URI_append += "file://0002-no-networkd-reset-if-IPSRC-same-only-DHCP-static-IPSRC-allowed.patch"
SRC_URI_append += "file://0003-after-set-IPSRC-static-able-to-set-Netmask.patch"
SRC_URI_append += "file://0004-Added-sys-interface-privilage.patch"
SRC_URI_append += "file://0005-implement-warm-reset-command.patch"
SRC_URI_append += "file://0006-Implement-System-Guid-and-Set-Channel-Security.patch"
SRC_URI_append += "file://0007-chassiscap.patch"
SRC_URI_append += "file://0008-removed-whitelisting-for-write-read.patch"
SRC_URI_append += "file://0009-switch-threading-to-asio-dbus.patch"
SRC_URI_append += "file://0010-system-boot-options.patch"
SRC_URI_append += "file://0011-sensor-reinitalization-after-cold-reset.patch"
SRC_URI_append += "file://0012-system-boot-options-mailbox-fix.patch"
SRC_URI_append += "file://0013-Added-dont-log-property.patch"
SRC_URI_append += "file://0014-local-global-check-for-MAC-address.patch"
SRC_URI_append += "file://0015-dcmi-activate-power-limit-reserved-length-fix.patch"
SRC_URI_append += "file://0016-dhcp-false-after-IPSRC-to-static.patch"
SRC_URI_append += "file://0017-reqdata-length-vaildation-dcmi-cmd.patch"
SRC_URI_append += "file://0018-added-watchdog-properties.patch"
SRC_URI_append += "file://0019-GetMsgFlags.patch"
SRC_URI_append += "file://0019-wdt-reset-unspported-when-reach-pretime-interval.patch"
SRC_URI_append += "file://0020-sys-interface-privilagecondition-check.patch"
SRC_URI_append += "file://0021-get-set-user-payload-for-non-created-users.patch"
SRC_URI_append += "file://0022-proper-error-msg-get-set-dcmi-configuration.patch"
SRC_URI_append += "file://0023-fixed-datalen-issue.patch"
SRC_URI_append += "file://0024-set-bmc-global-enable-cmd-priv-change.patch"
SRC_URI_append += "file://0025-return-invalid-for-IPSrc.patch"
SRC_URI_append += "file://0026-dcmi-getpowreading-fix.patch"
SRC_URI_append += "file://0027-check-duplicate-IP.patch"
SRC_URI_append += "file://0028-Fix-PowerCycle-on-power-off-state-Issue.patch"
SRC_URI_append += "file://0029-set-boot-parameters.patch"
SRC_URI_append += "file://0030-error-msg-dcmi-config-param2-reserved-bit.patch"
SRC_URI_append += "file://0031-DCMI-Vendor-Class-Identifier-Command.patch"
SRC_URI_append += "file://0032-Fix-error-code-return-for-set-dcmi-configuration.patch"
SRC_URI_append += "file://0033-system-boot-options-fixes-for-AMI-implementation.patch"
SRC_URI_append += "file://0034-get-payload-access-fix.patch"
SRC_URI_append += "file://0035-user-payload-access-fix.patch"
SRC_URI_append += "file://0036-Fix-keep-looping-issue-when-entering-OS.patch"
SRC_URI_append += "file://0037-Update-chassis-power-off-handler.patch"
SRC_URI_append += "file://0038-Systemd_Restart_Wrappper.patch"
SRC_URI_append += "file://0039-dcmi-sensors-cmd-support.patch"
SRC_URI_append += "file://0040-get-set-dcmi-power-limit.patch"

do_install_append(){
  install -d ${D}${includedir}/phosphor-ipmi-host
  install -m 0644 -D ${S}/sensorhandler.hpp ${D}${includedir}/phosphor-ipmi-host
  install -m 0644 -D ${S}/selutility.hpp ${D}${includedir}/phosphor-ipmi-host
}

