#!/bin/bash
#
# config: 1234 5
# @brief: Collect BMC state information.
#

. $DREPORT_INCLUDE/functions

desc="BMC State"
file_name="bmc-state.log"
command="busctl get-property \
                    xyz.openbmc_project.State.BMC \
                    /xyz/openbmc_project/state/bmc0 \
                    xyz.openbmc_project.State.BMC \
                    CurrentBMCState"

add_cmd_output "$command" "$file_name" "$desc"
