#!/bin/bash
#
# config: 1234 5
# @brief: Collect Chassis state information.
#

. $DREPORT_INCLUDE/functions

desc="Chassis State"
file_name="chassis-state.log"
command="busctl get-property \
                    xyz.openbmc_project.State.Chassis \
                    /xyz/openbmc_project/state/chassis0 \
                    xyz.openbmc_project.State.Chassis \
                    CurrentPowerState"

add_cmd_output "$command" "$file_name" "$desc"
