#!/bin/bash
#
# config: 2 40
# @brief: Print variables from primary flash U-Boot environment.
#

. $DREPORT_INCLUDE/functions

desc="PRI-Flash: U-Boot environment variables"
env_config="/etc/fw_env.config"

if [ ! -f $env_config ]; then
    log_error "$env_config does not exist"
    exit
fi


file_name="fw-printenv.log"
command="fw_printenv -c $env_config"

add_cmd_output "$command" "$file_name" "$desc"
