#!/bin/bash
#
# config: 2 30
# @brief: Collect ip link information.
#

. $DREPORT_INCLUDE/functions

desc="ip link"
file_name="iplink.log"
command="ip link"

add_cmd_output "$command" "$file_name" "$desc"
