#!/bin/bash
#
# config: 123 50
# @brief: Collect uptime information.
#

. $DREPORT_INCLUDE/functions

desc="uptime"
file_name="uptime.log"
command="uptime"

add_cmd_output "$command" "$file_name" "$desc"
